# Generated by Django 3.1.6 on 2021-02-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_create_sample_faq_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['sort_order']},
        ),
    ]
