# Generated by Django 3.1.6 on 2021-03-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='description',
            field=models.CharField(default=2, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='is_required_error',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='max_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='max_length_error',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='min_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='min_length_error',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='regex_chars',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='regex_chars_error',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
