# Generated by Django 3.1.6 on 2021-03-12 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa_field', '0002_auto_20210312_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='max_length',
        ),
        migrations.RemoveField(
            model_name='field',
            name='max_length_error',
        ),
        migrations.RemoveField(
            model_name='field',
            name='min_length',
        ),
        migrations.RemoveField(
            model_name='field',
            name='min_length_error',
        ),
        migrations.RemoveField(
            model_name='field',
            name='regex_chars',
        ),
        migrations.RemoveField(
            model_name='field',
            name='regex_chars_error',
        ),
        migrations.CreateModel(
            name='FieldText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_length', models.IntegerField(null=True)),
                ('min_length_error', models.CharField(max_length=250, null=True)),
                ('max_length', models.IntegerField(null=True)),
                ('max_length_error', models.CharField(max_length=250, null=True)),
                ('regex_chars', models.CharField(max_length=500, null=True)),
                ('regex_chars_error', models.CharField(max_length=250, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa_field.field')),
            ],
            options={
                'db_table': 'field_text',
            },
        ),
        migrations.CreateModel(
            name='FieldDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_kind', models.PositiveSmallIntegerField(choices=[(1, 'Байхгүй'), (2, '[Одоо]'), (3, 'Date')], db_index=True)),
                ('max_now_delta', models.DurationField(null=True)),
                ('max_date', models.DateField(null=True)),
                ('max_message', models.CharField(max_length=250, null=True)),
                ('min_kind', models.PositiveSmallIntegerField(choices=[(1, 'Байхгүй'), (2, '[Одоо]'), (3, 'Date')], db_index=True)),
                ('min_now_delta', models.DurationField(null=True)),
                ('min_date', models.DateField(null=True)),
                ('min_message', models.CharField(max_length=250, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa_field.field')),
            ],
            options={
                'db_table': 'field_date',
            },
        ),
    ]
