# Generated by Django 3.1.6 on 2021-03-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa_field', '0008_auto_20210316_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fielddate',
            old_name='max_message',
            new_name='max_date_error',
        ),
        migrations.RenameField(
            model_name='fielddate',
            old_name='min_message',
            new_name='min_date_error',
        ),
    ]
