# Generated by Django 3.1.6 on 2021-03-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_field', '0009_auto_20210316_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
