# Generated by Django 3.1.6 on 2021-04-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_field', '0012_auto_20210502_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
