# Generated by Django 3.1.6 on 2021-05-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_field', '0011_fieldchoice_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Text Field'), (2, 'Date Field'), (3, 'Choice Field'), (4, 'Nationality Field')], db_index=True),
        ),
    ]
