# Generated by Django 3.1.6 on 2021-03-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_countrylocale_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code_alpha2',
            field=models.CharField(db_index=True, default='000', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='code_alpha3',
            field=models.CharField(db_index=True, default='000', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='code_numeric',
            field=models.CharField(db_index=True, default='000', max_length=5),
            preserve_default=False,
        ),
    ]
