# Generated by Django 3.1.6 on 2021-04-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_auto_20210331_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='delete_at',
            field=models.DateTimeField(null=True),
        ),
    ]
