# Generated by Django 3.1.6 on 2021-04-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_country_delete_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='delete_at',
            new_name='deleted_at',
        ),
    ]
