# Generated by Django 3.1.6 on 2021-02-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0004_auto_20210224_1417'),
        ('country', '0005_auto_20210223_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.country')),
            ],
            options={
                'db_table': 'nationality',
            },
        ),
        migrations.CreateModel(
            name='NationalityLocale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='language.language')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nationality.nationality')),
            ],
            options={
                'db_table': 'nationality_locale',
            },
        ),
    ]
