# Generated by Django 3.1.6 on 2021-02-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_sample_languages'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='language',
            table='language',
        ),
    ]
