# Generated by Django 3.1.6 on 2021-02-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_auto_20210223_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code_name',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='language',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
