# Generated by Django 3.1.6 on 2021-02-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0005_auto_20210223_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa.document')),
            ],
            options={
                'db_table': 'document_field',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250)),
                ('code_name', models.CharField(db_index=True, max_length=50)),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'Text Field')], db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'field',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa.document')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('days_stay', models.PositiveSmallIntegerField()),
                ('days_valid', models.PositiveSmallIntegerField()),
                ('entry_kind', models.PositiveSmallIntegerField(choices=[(1, 'Single entry'), (2, 'Multiple entry')], db_index=True)),
                ('fee_visa', models.PositiveSmallIntegerField()),
                ('fee_person', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'visa_type',
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_arrival', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.country')),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa.visatype')),
            ],
            options={
                'db_table': 'visa',
            },
        ),
        migrations.CreateModel(
            name='ValueText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('document_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa.documentfield')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa.person')),
            ],
            options={
                'db_table': 'value_text',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='visa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa.visa'),
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('code_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa.field')),
            ],
            options={
                'db_table': 'field_choice',
            },
        ),
        migrations.AddField(
            model_name='documentfield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa.field'),
        ),
        migrations.AddField(
            model_name='document',
            name='visa_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa.visatype'),
        ),
    ]
