# Generated by Django 3.1.6 on 2021-03-04 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visa_document', '0001_initial'),
        ('visa_kind', '0001_initial'),
        ('country', '0006_countrylocale_nationality'),
        ('visa', '0002_auto_20210304_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa_document.document')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_arrival', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('visa_kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa_kind.visakind')),
            ],
            options={
                'db_table': 'visa',
            },
        ),
        migrations.CreateModel(
            name='ValueText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('document_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa_document.documentfield')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa.person')),
            ],
            options={
                'db_table': 'value_text',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='visa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa.visa'),
        ),
    ]
