# Generated by Django 3.1.6 on 2021-03-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0003_auto_20210304_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='number',
            field=models.CharField(default=1, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
