# Generated by Django 3.1.6 on 2021-03-21 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa_document', '0005_auto_20210314_1517'),
        ('visa', '0004_person_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField()),
                ('document_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa_document.documentfield')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa.person')),
            ],
            options={
                'db_table': 'value_date',
            },
        ),
        migrations.CreateModel(
            name='ValueChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('document_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa_document.documentfield')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa.person')),
            ],
            options={
                'db_table': 'value_choice',
            },
        ),
    ]
