# Generated by Django 3.1.6 on 2021-04-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0006_auto_20210325_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='days_stay',
            field=models.PositiveSmallIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visa',
            name='days_valid',
            field=models.PositiveSmallIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visa',
            name='entry_kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Single entry'), (3, 'Double entry'), (2, 'Multiple entry')], db_index=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visa',
            name='fee_person',
            field=models.PositiveSmallIntegerField(),
            preserve_default=False,
        ),
    ]
