# Generated by Django 3.1.6 on 2021-03-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0009_auto_20210414_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image_document',
            field=models.ImageField(default=1, upload_to='document/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='image_portrait',
            field=models.ImageField(default=3, upload_to='portait/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
