# Generated by Django 3.1.6 on 2021-03-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0010_auto_20210322_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image_document',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='image_portrait',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
