# Generated by Django 3.1.6 on 2021-03-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0011_auto_20210322_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image_document',
            field=models.ImageField(upload_to='document/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image_portrait',
            field=models.ImageField(default=3, upload_to='portait/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
