# Generated by Django 3.1.6 on 2021-04-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0012_auto_20210323_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image_document',
            field=models.ImageField(upload_to='govorg/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image_portrait',
            field=models.ImageField(upload_to='userprofile/'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='fee_person',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
