# Generated by Django 3.1.6 on 2021-04-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0014_auto_20210420_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image_document',
            field=models.ImageField(upload_to='person_document/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image_portrait',
            field=models.ImageField(upload_to='person_portrait/'),
        ),
    ]
