# Generated by Django 3.1.6 on 2021-04-21 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visa', '0015_auto_20210420_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='status',
        ),
        migrations.AddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New Request'), (2, 'Visa Approved'), (3, 'Visa Declined')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='image_document',
            field=models.ImageField(upload_to='image_document'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image_portrait',
            field=models.ImageField(upload_to='image_portrait'),
        ),
    ]
