# Generated by Django 3.1.6 on 2021-04-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0017_auto_20210421_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='updated_at_by',
            new_name='updated_by',
        ),
    ]
