# Generated by Django 3.1.6 on 2021-05-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa_document', '0007_remove_documentfield_description'),
        ('country', '0009_auto_20210408_1136'),
        ('visa', '0019_auto_20210426_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueNationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa_document.documentfield')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='country.country')),
            ],
            options={
                'db_table': 'value_nationality',
            },
        ),
    ]
