# Generated by Django 3.1.6 on 2021-05-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0021_auto_20210502_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValueNationality',
        ),
    ]
