# Generated by Django 3.1.6 on 2021-02-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error500',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_scheme', models.CharField(max_length=20, null=True)),
                ('request_url', models.CharField(max_length=500, null=True)),
                ('request_method', models.CharField(max_length=50, null=True)),
                ('request_headers', models.TextField(null=True)),
                ('request_data', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'error500',
            },
        ),
    ]
