# Generated by Django 3.1.6 on 2021-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error500', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='error500',
            name='request_body',
            field=models.TextField(null=True),
        ),
    ]
