# Generated by Django 3.1.6 on 2021-03-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisaPersonNumber',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
