# Generated by Django 3.1.6 on 2021-03-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa_person_number', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visapersonnumber',
            table='visa_person_number',
        ),
    ]
