# Generated by Django 3.1.6 on 2021-03-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_person_number', '0002_auto_20210305_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='visapersonnumber',
            name='length',
            field=models.PositiveSmallIntegerField(db_index=True, default=8),
            preserve_default=False,
        ),
    ]
