# Generated by Django 3.1.6 on 2021-03-04 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0006_countrylocale_nationality'),
        ('visa_field', '0001_initial'),
        ('visa', '0002_auto_20210304_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa_document.document')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa_field.field')),
            ],
            options={
                'db_table': 'document_field',
            },
        ),
        migrations.CreateModel(
            name='DocumentCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.country')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa_document.document')),
            ],
            options={
                'db_table': 'document_country',
            },
        ),
    ]
