# Generated by Django 3.1.6 on 2021-03-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_document', '0002_document_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
