# Generated by Django 3.1.6 on 2021-03-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa_document', '0003_document_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfield',
            options={'ordering': ['sort_order']},
        ),
    ]
