# Generated by Django 3.1.6 on 2021-03-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_document', '0004_auto_20210314_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
