# Generated by Django 3.1.6 on 2021-03-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_field', '0009_auto_20210316_0952'),
        ('visa_document', '0005_auto_20210314_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_field',
            field=models.ManyToManyField(through='visa_document.DocumentField', to='visa_field.Field'),
        ),
    ]
