# Generated by Django 3.1.6 on 2021-03-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa_document', '0006_document_document_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfield',
            name='description',
        ),
    ]
