# Generated by Django 3.1.6 on 2021-03-15 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210209_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='userContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('phone_no', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=2500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_contact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
