# Generated by Django 3.1.6 on 2021-03-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usercontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontact',
            name='email',
        ),
    ]
