# Generated by Django 3.1.6 on 2021-03-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_usercontact_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usercontact',
            table='user_contact',
        ),
    ]
