# Generated by Django 3.1.6 on 2021-03-04 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visa_document', '0001_initial'),
        ('visa', '0002_auto_20210304_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('days_stay', models.PositiveSmallIntegerField()),
                ('days_valid', models.PositiveSmallIntegerField()),
                ('entry_kind', models.PositiveSmallIntegerField(choices=[(1, 'Single entry'), (2, 'Multiple entry')], db_index=True)),
                ('fee_visa', models.PositiveSmallIntegerField()),
                ('fee_person', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'visa_kind',
            },
        ),
        migrations.CreateModel(
            name='VisaKindDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa_document.document')),
                ('visa_kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa_kind.visakind')),
            ],
            options={
                'db_table': 'visa_kind_document',
            },
        ),
    ]
