# Generated by Django 3.1.6 on 2021-03-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_countrylocale_nationality'),
        ('visa_document', '0001_initial'),
        ('visa_kind', '0002_visakind_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visakind',
            name='fee_visa',
        ),
        migrations.AddField(
            model_name='visakind',
            name='documents',
            field=models.ManyToManyField(through='visa_kind.VisaKindDocument', to='visa_document.Document'),
        ),
        migrations.CreateModel(
            name='VisaKindDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_person', models.PositiveSmallIntegerField()),
                ('percent', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visa_kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa_kind.visakind')),
            ],
            options={
                'db_table': 'visa_kind_discount',
            },
        ),
        migrations.CreateModel(
            name='VisaFeeExemptCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.country')),
                ('visa_kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa_kind.visakind')),
            ],
            options={
                'db_table': 'visafee_exempt_country',
            },
        ),
        migrations.CreateModel(
            name='VisaExemptCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.country')),
                ('visa_kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visa_kind.visakind')),
            ],
            options={
                'db_table': 'visa_exempt_country',
            },
        ),
    ]
