# Generated by Django 3.1.6 on 2021-03-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_countrylocale_nationality'),
        ('visa_kind', '0003_auto_20210317_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='visakind',
            name='fee_exempt_country',
            field=models.ManyToManyField(through='visa_kind.VisaExemptCountry', to='country.Country'),
        ),
    ]
