# Generated by Django 3.1.6 on 2021-03-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa_kind', '0004_visakind_fee_exempt_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visakind',
            old_name='fee_exempt_country',
            new_name='visa_exempt_country',
        ),
    ]
