# Generated by Django 3.1.6 on 2021-03-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_countrylocale_nationality'),
        ('visa_document', '0007_remove_documentfield_description'),
        ('visa_kind', '0006_auto_20210317_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visakind',
            name='documents',
            field=models.ManyToManyField(blank=True, through='visa_kind.VisaKindDocument', to='visa_document.Document'),
        ),
        migrations.AlterField(
            model_name='visakind',
            name='fee_exempt_country',
            field=models.ManyToManyField(blank=True, related_name='visa_fee_exempt_country', through='visa_kind.VisaFeeExemptCountry', to='country.Country'),
        ),
        migrations.AlterField(
            model_name='visakind',
            name='visa_exempt_country',
            field=models.ManyToManyField(blank=True, related_name='visa_exempt_country', through='visa_kind.VisaExemptCountry', to='country.Country'),
        ),
    ]
