# Generated by Django 3.1.6 on 2021-03-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_document', '0007_remove_documentfield_description'),
        ('visa_kind', '0007_auto_20210325_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visakind',
            name='documents',
            field=models.ManyToManyField(through='visa_kind.VisaKindDocument', to='visa_document.Document'),
        ),
    ]
