# Generated by Django 3.1.6 on 2021-03-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa_document', '0007_remove_documentfield_description'),
        ('country', '0006_countrylocale_nationality'),
        ('visa_kind', '0008_auto_20210326_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaexemptcountry',
            name='country',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='country.country'),
        ),
        migrations.AlterField(
            model_name='visafeeexemptcountry',
            name='country',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='country.country'),
        ),
        migrations.AlterField(
            model_name='visakinddocument',
            name='document',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='visa_document.document'),
        ),
    ]
