# Generated by Django 3.1.6 on 2021-03-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_kind', '0009_auto_20210326_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visakinddiscount',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
