# Generated by Django 3.1.6 on 2021-04-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_kind', '0010_auto_20210326_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visakind',
            name='entry_kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Single entry'), (3, 'Double entry'), (2, 'Multiple entry')], db_index=True),
        ),
    ]
