# Generated by Django 3.1.6 on 2021-04-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_kind', '0011_auto_20210408_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visakind',
            name='fee_person',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
