# Generated by Django 3.1.6 on 2021-05-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_kind', '0012_auto_20210420_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='visakind',
            name='code_name',
            field=models.CharField(max_length=5),
            preserve_default=False,
        ),
    ]
